# Generated by Django 3.2.6 on 2021-08-28 08:50

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='personal_id',
            field=models.IntegerField(default=university.models.generateStaffPersonalId, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=university.models.generateStudentPersonalId, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_id',
            field=models.IntegerField(default=university.models.generateTeacherPersonalId, unique=True),
        ),
    ]
