# Generated by Django 3.2.6 on 2021-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20210828_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='university.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='university.Staff'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='university.Staff'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='university.Student'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='university.Teacher'),
        ),
        migrations.AlterField(
            model_name='university',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='university.Staff'),
        ),
        migrations.AlterField(
            model_name='university',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='university.Student'),
        ),
        migrations.AlterField(
            model_name='university',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='university.Teacher'),
        ),
    ]
